#!/bin/bash

# bootstrap environment
source script/bootstrap

# nyc --extension .coffee mocha --require coffeescript "test/**/*.coffee"

# Switch to old style testing for the moment as newer test is broken because
# of class support issues
nyc --extension .coffee mocha --require coffeescript "test/tucker_test.coffee"
